# Generated by Django 2.2.6 on 2020-01-04 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('subject', models.CharField(max_length=20)),
                ('topics', models.CharField(max_length=150)),
            ],
        ),
    ]
