# Generated by Django 2.2.6 on 2020-01-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_TImeTable', '0002_auto_20200104_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='subject',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='time',
            field=models.CharField(max_length=30),
        ),
    ]
